layout(local_size_x = 8, local_size_y = 8) in;
#include "./GlobalDataBuffer.glsl"
layout(set = 1, binding = 0, rgba32f) uniform image2D outputImage;

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
//    vec4 outP = imageLoad(outputImage, coords);
//    if (length(outP) == 0){
//        for (int i = 0; i< 10000; i++){
//            imageStore(outputImage, coords, vec4(1));
//        }
//    }
    imageStore(outputImage, coords, vec4(1));
}