layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0, rgba32f) uniform image2D diSurfaceCacheImage;
layout(set = 1, binding = 0, rgba32f) uniform image2D diSurfaceCacheImageVisibility;

void main() {
    vec4 visibility = imageLoad(diSurfaceCacheImageVisibility, ivec2(gl_GlobalInvocationID.xy));
    if (visibility.r != 1){
        imageStore(diSurfaceCacheImage, ivec2(gl_GlobalInvocationID.xy), vec4(0, 0, 0, 1));
    }
}
